---
abstract: 'Detect terminal (emulator) software and its capabilities'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Term-Detect-Software
requires:
  SHARYANTO::Proc::Util: 0.44
  experimental: 0
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Term-Detect-Software
  repository: http://github.com/sharyanto/perl-Term-Detect-Software
version: 0.09
